version: '3.7'

services:
  web:
    restart: unless-stopped
    container_name: roblox_crawler_web
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./web-runner.sh
    env_file:
      - .env
    volumes:
      - ./static:/app/static
    expose:
      - "8000"
    depends_on:
      - postgres

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: roblox_crawler_celery
    env_file:
      - .env
    command: bash -c "celery -A tasks worker --uid crawlercelery --loglevel INFO --logfile ./static/celery.log"
    volumes:
      - ./static:/app/static
    depends_on:
      - redis
      - web

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: roblox_crawler_web_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  postgres:
    image: postgres:alpine
    restart: always
    container_name: roblox_crawler_postgres
    env_file:
      - .env
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}'
    expose:
      - '${POSTGRES_INTERNAL_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: 'redis:alpine'
    restart: always
    container_name: roblox_crawler_redis
    hostname: roblox_crawler_redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD:?err}
    expose:
      - "6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
